apps/preregistros/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url
from .views import *

urlpatterns = [

    url(r'generar_matricula/(?P<id_preregistro>\d+)/$', 'apps.preregistros.views.generar_matricula',
        name='generar_matricula'),

    url(r'success/$', 'apps.preregistros.views.preregistro_success', name='preregistro_success'),

    url(r'crear/$', 'apps.preregistros.views.crear_preregistro', name='crear'),
    url(r'comprobantes_actividad/(?P<id_preregistro>\d+)/$', ComprobantesActividadView.as_view(),
        name='comprobantes_actividad'),

    url(r'(?P<id_preregistro>\d+)/$', 'apps.preregistros.views.detalle_preregistro', name='detalle_preregistro'),

    url(r'$', 'apps.preregistros.views.ver_preregistros', name='preregistros'),
]

django_project/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.main.urls', namespace='main_app')),
    url(r'^', include('apps.miembros.urls', namespace='miembros_app')),
    url(r'^eventos/', include('apps.eventos.urls', namespace='eventos_app')),
    url(r'^difusion/', include('apps.difusion.urls', namespace='difusion_app')),
    url(r'^preregistros/', include('apps.preregistros.urls', namespace='preregistros_app')),
    url(r'^CIR/', include('apps.CIR.urls', namespace='cir_app')),

    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^redactor/', include('redactor.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

from django.conf import settings

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

apps/preregistros/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.utils.datetime_safe import *


class Preregistro(models.Model):
    nombre = models.CharField(max_length=500)
    email = models.EmailField()
    telefono = models.CharField(max_length=13)
    escuela = models.CharField(max_length=100)
    comprobante_estudios = models.FileField(upload_to='preregistros/comprobantes_estudios')
    fecha_preregistro = models.DateField(default=datetime.now)

    class Meta:
        verbose_name = 'Pre Registro'
        verbose_name_plural = 'Pre Registros'

    def __str__(self):
        return self.nombre


class ComprobanteActividad(models.Model):
    preregistro = models.ForeignKey(Preregistro)
    comprobante_actividad = models.FileField(upload_to='preregistros/comprobantes_actividad')

    class Meta:
        verbose_name = 'Comprobante de Actividad'
        verbose_name_plural = 'Comprobantes de Actividad'

    def __str__(self):
        return '%s - %s' % (self.preregistro, self.comprobante_actividad)

apps/preregistros/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from multiupload.fields import MultiFileField
from .models import *


class PreregistroForm(forms.ModelForm):
    class Meta:
        model = Preregistro
        fields = ('nombre', 'email', 'telefono', 'escuela', 'comprobante_estudios')

        widgets = {
            'nombre': forms.TextInput(attrs={
                'placeholder': 'Nombre Completo',
                'class': 'form-control',
            }),
            'email': forms.TextInput(attrs={
                'placeholder': 'Email',
                'class': 'form-control',
            }),
            'telefono': forms.TextInput(attrs={
                'placeholder': 'Telefono de Contacto',
                'class': 'form-control',
            }),
            'escuela': forms.TextInput(attrs={
                'placeholder': 'Escuela Superior',
                'class': 'form-control',
            }),
            'comprobante_estudios': forms.FileInput()
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data


class ComprobanteActividadForm(forms.Form):
    comprobante_actividad = MultiFileField(min_num=1, max_num=5, max_file_size=1024 * 1024 * 10)

apps/preregistros/views.py
# -*- encoding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render_to_response
from django.views.generic import FormView
import datetime

from .forms import *
from apps.miembros.models import Miembro

# Create your views here.

def crear_preregistro(request):
    preregistro_form = PreregistroForm()

    if request.method == 'POST':
        print(request.POST)
        if 'preregistro_form' in request.POST:
            preregistro_form = PreregistroForm(request.POST, request.FILES)
            if preregistro_form.is_valid():
                nuevo_preregistro = preregistro_form.save()
                return redirect(reverse_lazy('preregistros_app:comprobantes_actividad',
                                             kwargs={'id_preregistro': nuevo_preregistro.id}))
            else:
                print('registro incompleto')

    return render(request, 'preregistros/preregistro.html', {'preregistro_form': preregistro_form})

@permission_required('preregistros.add_preregistro')
def ver_preregistros(request):
    preregistros = Preregistro.objects.all().order_by('-fecha_preregistro')
    return render(request, 'preregistros/ver_preregistros.html', {'preregistros': preregistros})


class ComprobantesActividadView(FormView):
    template_name = 'preregistros/comprobantes_actividad.html'
    form_class = ComprobanteActividadForm
    success_url = '/preregistros/success/'

    def form_valid(self, form):
        id_preregistro = int(self.kwargs['id_preregistro'])
        print(id_preregistro)
        preregistro = Preregistro.objects.get(id=id_preregistro)

        for each in form.cleaned_data['comprobante_actividad']:
            ComprobanteActividad.objects.create(preregistro=preregistro,
                                                comprobante_actividad=each)

        return super(ComprobantesActividadView, self).form_valid(form)


@permission_required('preregistros.add_preregistro')
def detalle_preregistro(request, id_preregistro):
    preregistro = Preregistro.objects.get(id=id_preregistro)
    comprobantes_actividad = ComprobanteActividad.objects.filter(preregistro=preregistro)

    return render_to_response('preregistros/detalle_preregistro.html',
                              {'preregistro': preregistro,
                               'comprobantes_actividad': comprobantes_actividad})



def preregistro_success(request):
    return render_to_response('preregistros/preregistro_success.html')


def generar_matricula(request, id_preregistro):
    preregistro = get_object_or_404(Preregistro, pk=id_preregistro)

    now = datetime.now()

    nuevo_miembro, created = Miembro.objects.get_or_create(email=preregistro.email, nombre=preregistro.nombre)
    nueva_matricula = 'CPR{0}{1}'.format(now.year, str(nuevo_miembro.id).zfill(4))
    nuevo_miembro.matricula = nueva_matricula
    nuevo_miembro.email = preregistro.email
    nuevo_miembro.nombre = preregistro.nombre
    nuevo_miembro.set_password(nueva_matricula)
    nuevo_miembro.save()

    preregistro.delete()

    from django.core.mail import send_mail
    send_mail("Asunto",
          "Felicidades %s, tu nueva cuenta es:\nMatricula: %s\nPassword: %s" % (nuevo_miembro.nombre, nueva_matricula, nueva_matricula),
          'cpr.stage1@gmail.com',
          [nuevo_miembro.email])

    return redirect(reverse('preregistros_app:preregistros'))

templates/preregistros/comprobantes_actividad.html
{% extends 'base.html' %}

{% block title %}
    Comprobantes de Actividad
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}

    <div class="row row-centered">
        <div class="col-md-4 col-centered">

            <h2>Comprobantes</h2>
            <h5>{{ Error }}</h5>

            <form method="post" accept-charset="utf-8" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <!-- Render the field label tag -->
                        {{ field.label }}
                        {{ field }}
                        <!--  muestra los errores que halla en los fields -->
                        {% if field.errors %}
                            <p class="text-danger">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            </p>
                        {% endif %}
                    </div>
                {% endfor %}
                <button class="btn btn-primary m-b pull-right" type="submit" name="preregistro_form">Enviar
                </button>
            </form>

        </div>
    </div>

{% endblock %}

{% block scripts %}

{% endblock %}

templates/preregistros/detalle_preregistro.html
{% extends 'base.html' %}

{% block title %}
    Preregistro
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}

    <div class="row row-centered">
        <div class="col-sm-10 col-centered">
            <div class="col-sm-8">
                <h1>Preregistro</h1>

                <h3>{{ preregistro.nombre }}</h3>
                <h5>{{ preregistro.email }}</h5>
                <h5>{{ preregistro.telefono }}</h5>
                <h5>{{ preregistro.escuela }}</h5>
                <a href="{% url 'preregistros_app:generar_matricula' preregistro.id %}" class="btn btn-primary">Generar
                    Matrícula</a>
            </div>
            <div class="col-sm-4">
                <h4>Comprobante de Estudios</h4>
                <a href="{{ preregistro.comprobante_estudios.url }}">
                    <img class="img-responsive img-rounded" src="{{ preregistro.comprobante_estudios.url }}"
                         alt="Comprobante de Estudios"/>
                </a>
            </div>

            <div class="col-sm-12">
                <hr/>
                <h4>Comprobante(s) de Actividad</h4>
                {% if comprobantes_actividad.count == 0 %}
                    <h5>No hay Comprobantes de actividad</h5>
                {% endif %}
                {% for comprobante in comprobantes_actividad %}
                    <div class="col-sm-4">
                        <a href="{{ comprobante.comprobante_actividad.url }}">
                            <img class="img-responsive img-rounded" src="{{ comprobante.comprobante_actividad.url }}"
                                 alt="Comprobante de Actividad"/>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}

{% endblock %}

templates/preregistros/preregistro.html
{% extends 'base.html' %}

{% block title %}
    Inicia Sesión
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}

    <div class="row row-centered">
        <div class="col-md-4 col-centered">
            {% if preregistro_form %}
                <h2>Pre Registro</h2>
                <h5>{{ Error }}</h5>
                <form method="post" accept-charset="utf-8" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in preregistro_form %}
                        <div class="form-group">
                            <!-- Render the field label tag -->
                            {{ field.label }}
                            {{ field }}
                            <!--  muestra los errores que halla en los fields -->
                            {% if field.errors %}
                                <p class="text-danger">
                                    {% for error in field.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </p>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button class="btn btn-primary m-b pull-right" type="submit" name="preregistro_form">Regístrate
                    </button>
                </form>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block scripts %}

{% endblock %}

templates/preregistros/preregistro_success.html
{% extends 'base.html' %}

{% block title %}
    Preregistro Exitoso
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-xs-12">
            <div class="jumbotron">
                <h1>
                    Felicidades
                </h1>

                <p>Tu Pre Registro ha sido enviado correctamente</p>
                <small>Te enviaremos un correo cuando seas aceptado</small>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}

{% endblock %}

templates/preregistros/ver_preregistros.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    Title
{% endblock %}


{% block styles %}

{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-4">
            <div class="list-group">
                {% for preregistro in preregistros %}
                    <a href="{% url 'preregistros_app:detalle_preregistro' preregistro.id %}">
                        <div class="list-group-item">
                            <div class="row-picture">
                                <img class="circle" src="http://lorempixel.com/56/56/people/6" alt="icon">
                            </div>
                            <div class="row-content">
                                <h4 class="list-group-item-heading">{{ preregistro.nombre }}</h4>

                                <p class="list-group-item-text">{{ preregistro.fecha_preregistro|date }}</p>
                            </div>
                        </div>
                        <div class="list-group-separator"></div>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}