apps/difusion/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^noticias/$', 'apps.difusion.views.ver_noticias', name='ver_noticias'),
    url(r'^noticias/(?P<id_noticia>\d+)/$', 'apps.difusion.views.detalle_noticia', name='detalle_noticia'),
    url(r'^noticias/editar/(?P<id_noticia>\d+)/$', 'apps.difusion.views.editar_noticia', name='editar_noticia'),
    url(r'^noticias/crear/$', 'apps.difusion.views.crear_noticia', name='crear_noticia'),
]

django_project/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.main.urls', namespace='main_app')),
    url(r'^', include('apps.miembros.urls', namespace='miembros_app')),
    url(r'^eventos/', include('apps.eventos.urls', namespace='eventos_app')),
    url(r'^difusion/', include('apps.difusion.urls', namespace='difusion_app')),
    url(r'^preregistros/', include('apps.preregistros.urls', namespace='preregistros_app')),
    url(r'^CIR/', include('apps.CIR.urls', namespace='cir_app')),

    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^redactor/', include('redactor.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

from django.conf import settings

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

apps/difusion/models.py
from django.db import models


class Noticia(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    fecha_creacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.titulo

apps/difusion/forms.py
from django import forms

from redactor.widgets import RedactorEditor
from .models import *


class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ('titulo', 'contenido')

        widgets = {
            'titulo': forms.TextInput(attrs={
                'type': 'text',
                'class': 'form-control',
            }),
            'contenido': RedactorEditor(attrs={
                'class': 'form-control'
            }),
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data

apps/difusion/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import render_to_response
from .models import *
from .forms import NoticiaForm


def ver_noticias(request):
    noticias = Noticia.objects.all().order_by('-fecha_creacion')
    return render(request, 'difusion/ver_noticias.html', {'noticias': noticias})


def detalle_noticia(request, id_noticia):
    noticia = get_object_or_404(Noticia, pk=id_noticia)
    return render(request, 'difusion/detalle_noticia.html', {'noticia': noticia})


def crear_noticia(request):
    noticia_form = NoticiaForm()
    if request.method == 'POST':
        noticia_form = NoticiaForm(request.POST)
        if 'noticia_form' in request.POST:
            if noticia_form.is_valid():
                noticia_form.save()
                return redirect(reverse('difusion_app:ver_noticias'))

    return render(request, 'difusion/crear_noticia.html', {'noticia_form': noticia_form})


def editar_noticia(request, id_noticia):
    noticia = get_object_or_404(Noticia, pk=id_noticia)
    noticia_form = NoticiaForm(instance=noticia)
    if request.method == 'POST':
        noticia_form = NoticiaForm(request.POST, instance=noticia)
        if 'noticia_form' in request.POST:
            if noticia_form.is_valid():
                noticia_form.save()
                return redirect(reverse('difusion_app:ver_noticias'))
        elif 'borrar_noticia' in request.POST:
            noticia.delete()
            return redirect(reverse('difusion_app:ver_noticias'))

    return render(request, 'difusion/editar_noticia.html', {'noticia_form': noticia_form})

templates/difusion/crear_noticia.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    Noticias
{% endblock %}


{% block styles %}

{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-8 well">
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ noticia_form.media }}
                {% for field in noticia_form %}
                    <div class="form-group">
                        <p>{{ field.label }}</p>
                        {{ field }}
                    </div>
                {% endfor %}

                <button class="btn btn-info" type="submit" name="noticia_form">Crear Noticia</button>
            </form>
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}

templates/difusion/detalle_noticia.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    Noticias
{% endblock %}


{% block styles %}
    <style>
        .contenido img {
            width: 100%;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h1>{{ noticia.titulo }}
                <small>{{ noticia.fecha_creacion|date }}</small>
            </h1>

            <span class="contenido">
                {{ noticia.contenido|safe }}
            </span>
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}

templates/difusion/editar_noticia.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    Noticias
{% endblock %}


{% block styles %}

{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-8 well">
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ noticia_form.media }}
                {% for field in noticia_form %}
                    <div class="form-group">
                        <p>{{ field.label }}</p>
                        {{ field }}
                    </div>
                {% endfor %}

                <button class="btn btn-info" type="submit" name="noticia_form">Crear Noticia</button>
                <button class="btn btn-danger" type="submit" name="borrar_noticia">Eliminar Noticia</button>
            </form>
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}

templates/difusion/ver_noticias.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    Noticias
{% endblock %}


{% block styles %}

{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h1>Noticias</h1>
            {% if perms.difusion.add_noticia %}
                <a class="btn btn-info" href="{% url 'difusion_app:crear_noticia' %}">Crear Noticia</a>
            {% endif %}
            <hr/>
            <div class="list-group">
                {% for noticia in noticias %}
                    <a href="{% url 'difusion_app:detalle_noticia' noticia.id %}">
                        <div class="list-group-item">
                            <div class="row-picture">
                                <i class="mdi-action-info-outline"></i>
                            </div>
                            <div class="row-content">
                                <h4 class="list-group-item-heading">
                                    {{ noticia.titulo }}
                                    {% if perms.difusion.add_noticia %}
                                        <a class="pull-right" href="{% url 'difusion_app:editar_noticia' noticia.id %}">Editar</a>
                                    {% endif %}
                                </h4>

                                <p class="list-group-item-text">{{ noticia.fecha_creacion|date }}</p>
                            </div>
                        </div>
                    </a>
                    <div class="list-group-separator"></div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}