apps/eventos/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/$', 'apps.eventos.views.eventos_admin', name='eventos_admin'),
    url(r'^admin/crear/$', 'apps.eventos.views.crear_evento_admin', name='crear_evento_admin'),
    url(r'^admin/editar/(?P<id_evento>\d+)/$', 'apps.eventos.views.editar_evento_admin', name='editar_evento_admin'),
    url(r'^logout/$', 'apps.miembros.views.logout_miembro', name='logout'),

    url(r'^gestion_miembros/$', 'apps.miembros.views.gestion_miembros', name='gestion_miembros'),
    url(r'^editar_miembro/(?P<id_miembro>\d+)/$', 'apps.miembros.views.editar_miembro', name='editar_miembro'),
]

django_project/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.main.urls', namespace='main_app')),
    url(r'^', include('apps.miembros.urls', namespace='miembros_app')),
    url(r'^eventos/', include('apps.eventos.urls', namespace='eventos_app')),
    url(r'^difusion/', include('apps.difusion.urls', namespace='difusion_app')),
    url(r'^preregistros/', include('apps.preregistros.urls', namespace='preregistros_app')),
    url(r'^CIR/', include('apps.CIR.urls', namespace='cir_app')),

    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^redactor/', include('redactor.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

from django.conf import settings

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

apps/eventos/models.py
from django.db import models
from apps.miembros.models import *


class EventosAdmin(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha = models.DateTimeField()

    class Meta:
        verbose_name = 'Evento Administrativo'
        verbose_name_plural = 'Eventos Administrativos'

    def __str__(self):
        return self.titulo

apps/eventos/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from .models import *
from datetimewidget.widgets import DateTimeWidget


class EventoForm(forms.ModelForm):
    class Meta:
        model = EventosAdmin
        fields = ('titulo', 'descripcion', 'fecha')

        widgets = {
            'titulo': forms.TextInput(attrs={
                'placeholder': 'Titulo',
                'class': 'form-control',
            }),
            'descripcion': forms.TextInput(attrs={
                'placeholder': 'Descripcion',
                'class': 'form-control',
            }),
            'fecha': DateTimeWidget(attrs={'id': "yourdatetimeid"}, usel10n=True, bootstrap_version=3)
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        return cleaned_data

apps/eventos/views.py
# -*- encoding: utf-8 -*-
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render, redirect
from .forms import *
from .models import *


def eventos_admin(request):
    eventos_admin = EventosAdmin.objects.all()
    return render(request, 'eventos/eventos_admin.html',
                  {'eventos_admin': eventos_admin})


def crear_evento_admin(request):
    evento_form = EventoForm()
    if request.method == 'POST':
        evento_form = EventoForm(request.POST)
        if 'evento_form' in request.POST:
            if evento_form.is_valid():
                evento_form.save()
                return redirect(reverse('eventos_app:eventos_admin'))

    return render(request, 'eventos/crear_evento_admin.html',
                  {'evento_form': evento_form})


def editar_evento_admin(request, id_evento):
    evento = EventosAdmin.objects.get(id=id_evento)
    evento_form = EventoForm(instance=evento)
    if request.method == 'POST':
        if 'evento_form' in request.POST:
            evento_form = EventoForm(request.POST, instance=evento)
            if evento_form.is_valid():
                evento_form.save()
                return redirect(reverse_lazy('eventos_app:eventos_admin'))
        elif 'borrar_evento' in request.POST:
            evento.delete()
            return redirect(reverse_lazy('eventos_app:eventos_admin'))

    return render(request, 'eventos/editar_evento_admin.html', {'evento': evento,
                                                                'evento_form': evento_form})

templates/eventos/crear_evento_admin.html
{% extends 'base.html' %}

{% block title %}
    Crear Evento
{% endblock %}

{% block styles %}
    {{ evento_form.media }}
{% endblock %}

{% block content %}

    <div class="row row-centered">
        <div class="col-md-4 col-centered well">

            <h5>{{ Error }}</h5>

            <form method="post" accept-charset="utf-8" enctype="multipart/form-data">
                {% csrf_token %}
                {{ evento_form.as_p }}
                <button class="btn btn-danger m-b" type="submit" name="borrar_evento">Eliminar</button>
                <button class="btn btn-primary m-b" type="submit" name="evento_form">Guardar</button>
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}

{% endblock %}

templates/eventos/editar_evento_admin.html
{% extends 'base.html' %}

{% block title %}
    Editar Evento
{% endblock %}

{% block styles %}
    {{ evento_form.media }}
{% endblock %}

{% block content %}

    <div class="row row-centered">
        <div class="col-md-4 col-centered well">
            {% if evento_form %}
                <h5>{{ Error }}</h5>
                <form method="post" accept-charset="utf-8" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in evento_form %}
                        <div class="form-group">
                            <!-- Render the field label tag -->
                            {{ field.label }}
                            {{ field }}
                            <!--  muestra los errores que halla en los fields -->
                            {% if field.errors %}
                                <p class="text-danger">
                                    {% for error in field.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </p>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button class="btn btn-danger m-b" type="submit" name="borrar_evento">Eliminar</button>
                    <button class="btn btn-primary m-b" type="submit" name="evento_form">Guardar</button>
                </form>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block scripts %}

{% endblock %}

templates/eventos/eventos_admin.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    Eventos Administrativos
{% endblock %}


{% block styles %}

{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h1>Eventos Administrativos</h1>
            <a href="{% url 'eventos_app:crear_evento_admin' %}" class="btn btn-primary">Crear Evento</a>
            <hr/>
            <div class="list-group">
                {% for evento in eventos_admin %}
                    <a href="{% url 'eventos_app:editar_evento_admin'  evento.id %}">
                        <div class="list-group-item">
                            <div class="row-picture">
                                <i class="mdi-action-event"></i>
                            </div>
                            <div class="row-content">
                                <h4 class="list-group-item-heading">{{ evento.titulo }}</h4>
                                <h4 class="list-group-item-text">{{ evento.descripcion }}</h4>

                                <p class="list-group-item-text">{{ evento.fecha|date }}</p>
                            </div>
                        </div>
                    </a>
                    <div class="list-group-separator"></div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}

{% endblock %}