apps/CIR/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^inscribirse/$', 'apps.CIR.views.inscripcion_competencia', name='inscribirse'),
    url(r'^inscripciones/$', 'apps.CIR.views.ver_inscripciones', name='ver_inscripciones'),
    url(r'^inscripciones/(?P<id_inscripcion>\d+)/$', 'apps.CIR.views.detalle_inscripcion', name='detalle_inscripcion'),
]

apps/difusion/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^noticias/$', 'apps.difusion.views.ver_noticias', name='ver_noticias'),
    url(r'^noticias/(?P<id_noticia>\d+)/$', 'apps.difusion.views.detalle_noticia', name='detalle_noticia'),
    url(r'^noticias/editar/(?P<id_noticia>\d+)/$', 'apps.difusion.views.editar_noticia', name='editar_noticia'),
    url(r'^noticias/crear/$', 'apps.difusion.views.crear_noticia', name='crear_noticia'),
]

apps/eventos/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/$', 'apps.eventos.views.eventos_admin', name='eventos_admin'),
    url(r'^admin/crear/$', 'apps.eventos.views.crear_evento_admin', name='crear_evento_admin'),
    url(r'^admin/editar/(?P<id_evento>\d+)/$', 'apps.eventos.views.editar_evento_admin', name='editar_evento_admin'),
    url(r'^logout/$', 'apps.miembros.views.logout_miembro', name='logout'),

    url(r'^gestion_miembros/$', 'apps.miembros.views.gestion_miembros', name='gestion_miembros'),
    url(r'^editar_miembro/(?P<id_miembro>\d+)/$', 'apps.miembros.views.editar_miembro', name='editar_miembro'),
]

apps/main/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^$', 'apps.main.views.index', name='index'),
]

django_project/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.main.urls', namespace='main_app')),
    url(r'^', include('apps.miembros.urls', namespace='miembros_app')),
    url(r'^eventos/', include('apps.eventos.urls', namespace='eventos_app')),
    url(r'^difusion/', include('apps.difusion.urls', namespace='difusion_app')),
    url(r'^preregistros/', include('apps.preregistros.urls', namespace='preregistros_app')),
    url(r'^CIR/', include('apps.CIR.urls', namespace='cir_app')),

    url(r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^redactor/', include('redactor.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

from django.conf import settings

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="es-MX">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | CPR Stage</title>

    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="{% static 'base/js/jquery.datetimepicker.js' %}"></script>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Include roboto.css to use the Roboto web font, material.css to include the theme and ripples.css to style the ripple effect -->
    <link href="{% static 'main/css/roboto.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/material.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/material-fullpalette.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/ripples.min.css' %}" rel="stylesheet">

    <link href="//fezvrasta.github.io/snackbarjs/dist/snackbar.min.css" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'base/css/style.css' %}" rel="stylesheet">

    {% block styles %}

    {% endblock %}

    <style>
        body{
            overflow-x: hidden;
        }
    </style>

</head>

<body>

    <!-- Your site -->

    <div class="navbar navbar-default navbar-material-pink-900">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'main_app:index' %}">CPR Stage</a>
        </div>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">

                {% if perms.preregistros.add_preregistro %}
                    <li class="dropdown">
                        <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle"
                           data-toggle="dropdown">Administración <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'miembros_app:gestion_miembros' %}">Gestionar Miembros</a></li>
                            <li><a href="{% url 'preregistros_app:preregistros' %}">Ver Preregistros</a></li>
                            <li><a href="{% url 'eventos_app:eventos_admin' %}">Eventos Administrativos</a></li>
                        </ul>
                    </li>
                {% endif %}

                {% if perms.difusion.add_noticia %}
                    <li class="dropdown">
                        <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle"
                           data-toggle="dropdown">Difusión <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'difusion_app:ver_noticias' %}">Ver Noticias</a></li>
                            <li><a href="{% url 'difusion_app:crear_noticia' %}">Crear Noticia</a></li>
                        </ul>
                    </li>
                {% endif %}

                {% if perms.difusion.add_competencia %}
                    <li class="dropdown">
                        <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle"
                           data-toggle="dropdown">CIR <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'cir_app:inscribirse' %}">Ver equipos inscritos</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'cir_app:inscribirse' %}">Inscripción a Competencia</a></li>
                {% if user.is_authenticated %}
                     <li class="dropdown">
                         <a href="" class="dropdown-toggle" data-toggle="dropdown">{{ user.nombre }}</a>
                         <ul class="dropdown-menu">
                            <li><a href="javascript:void(0)">Mi perfil</a></li>
                             <li><a href="{% url 'miembros_app:editar_miembro' user.id %}">Configuración</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'miembros_app:logout' %}">Salir</a></li>
                         </ul>
                     </li>
                {% else %}
                    <li><a href="{% url 'preregistros_app:crear' %}">Pre Registro</a></li>
                    <li><a href="{% url 'miembros_app:login' %}">Iniciar Sesión</a></li>
                {% endif %}
            </ul>
        </div>
    </div>

    <div class="page-wrapper" style="padding: 50px">

    {% block content %}

    {% endblock %}

    </div>



    <!-- Your site ends -->

    <script src="{% static 'main/js/ripples.min.js' %}"></script>
    <script src="{% static 'main/js/material.min.js' %}"></script>

    <script src="//fezvrasta.github.io/snackbarjs/dist/snackbar.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/noUiSlider/6.2.0/jquery.nouislider.min.js"></script>

    <script>
        $(document).ready(function() {
            // This command is used to initialize some elements and make them work properly
            $.material.init();
        });
    </script>

    {% block scripts %}

    {% endblock %}

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
Inicio
{% endblock %}

{% block styles %}
    <style>
        .div-noticia {
            background-color: #FAFAFA;
            padding: 5px 20px;
            box-shadow: 0 1.5px 4px rgba(0, 0, 0, 0.24), 0 1.5px 6px rgba(0, 0, 0, 0.12);
        }

    </style>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-xs-12">
            <div class="div-noticia">
                <h1>
                    Bienvenido
                    {% if user.is_authenticated %}
                        {{ user.nombre }}
                    {% endif %}
                </h1>
                <p>La plataforma de gestión de la Comunidad Politécnica de Robótica - IPN</p>
            </div>
        </div>
    </div>
    <hr/>
    <h1>Noticias, competencias e información</h1>
    {% for noticia in noticias %}
        <div class="row">
            <div class="col-md-8 div-noticia">

                <h2>
                    <a href="{% url 'difusion_app:detalle_noticia' noticia.id %}">{{ noticia.titulo }}</a>
                    <small>{{ noticia.fecha_creacion|date }}</small>
                </h2>

            <span class="contenido">
                {{ noticia.contenido|safe }}
            </span>
            </div>
        </div>
        <hr/>
    {% endfor %}
{% endblock %}

{% block scripts %}

    <script>
        $(document).ready(function () {
            $('.div-noticia img').addClass('img-responsive');
        });
    </script>
{% endblock %}